name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main  # The branch to monitor for changes

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ensure this matches your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as needed

    - name: Run tests
      run: |
        pytest  # Make sure you have tests in your FastAPI project

    - name: Build FastAPI app
      run: |
        uvicorn app:app --host 0.0.0.0 --port 8000 --reload

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12  # Action to deploy to Heroku
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'your-heroku-app-name'  # Replace with your Heroku app name
        heroku_email: 'your-email@example.com'  # Your Heroku account email
